version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cocinaencasa_2
    environment:
      - APPLICATION_PORT=3310
      - DATABASE_URL=postgres://miybplwbbxzlqk:d1e2f70bb309f91f1ba2a3fe0e45d42a3db287433b9c346ccd5b13d653231e8e@ec2-34-225-82-212.compute-1.amazonaws.com:5432/d46mseap186jlh
      - DATABASE_SCHEMA=public
      - DATABASE_SSL=true
      - FOREST_AUTH_SECRET=cd069b835ec078d55ae66a73105e6e8d83169ee8dd656f2685faae71f270e688a83930d282cb0d2af047daee3b42512f
      - FOREST_ENV_SECRET=f396256bc3186dd6dbbe7e159e3e2f8d62feae669115ab6aab184e1dba28ed1d
    ports:
      - "3310:3310"
    volumes:
      - ./:/usr/src/app
